name: Train and Publish Model

on:
  workflow_dispatch:
    inputs:
      epochs_frozen:
        description: 'Number of epochs for frozen layers'
        required: false
        default: '5'
        type: number
      epochs_unfrozen:
        description: 'Number of epochs for unfrozen layers'
        required: false
        default: '10'
        type: number
      lr_frozen:
        description: 'Learning rate for frozen layers'
        required: false
        default: '1e-3'
        type: string
      lr_unfrozen:
        description: 'Learning rate for unfrozen layers'
        required: false
        default: '1e-5'
        type: string

jobs:
  train-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install huggingface_hub

    - name: Clean up Docker resources before build
      run: docker system prune -af --volumes
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install

    - name: Debug Hugging Face Authentication
      run: |
        echo "Setting up Hugging Face credentials..."
        pip install huggingface_hub
        echo "${{ secrets.HUGGINGFACE_TOKEN }}" | huggingface-cli login --token-stdin
        echo "Checking authentication status:"
        huggingface-cli whoami
        echo "Listing available spaces:"
        huggingface-cli repo list --spaces

    - name: Run the auto training script
      run: |
        chmod +x auto_train.sh
        # Set environment variable to indicate we're in GitHub Actions
        export GITHUB_ACTIONS=true
        export HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
        ./auto_train.sh --epochs-frozen ${{ github.event.inputs.epochs_frozen }} \
                        --epochs-unfrozen ${{ github.event.inputs.epochs_unfrozen }} \
                        --lr-frozen ${{ github.event.inputs.lr_frozen }} \
                        --lr-unfrozen ${{ github.event.inputs.lr_unfrozen }}
      env:
        # Make token available to the script
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

    - name: Clean up Docker resources after build
      run: docker system prune -af --volumes
      if: always()  # Run this step even if previous steps fail
